---
meta:
  default:
    azs: [z1]
    tags:
      - queue=default
      - docker-available

params:
  instances: 1
  network:   default
  vm_type:   default

  aws_access_key: (( param "Please specify your AWS Access Key ID" ))
  aws_secret_key: (( param "Please specify your AWS Secret Access Key" ))
  aws_region:     (( param "Please specify your Amazon AWS Region" ))

  buildkite_token: (( param "Please specify your Buildkite API Token" ))

  agent_environment: ''
  #agent_tags: []

instance_groups:
  - name:      buildkite-agent
    instances: (( grab params.instances ))
    azs:       (( grab params.availability_zones || meta.default.azs ))
    stemcell:  default
    networks:  [{ name: (( grab params.network )) }]
    vm_type:   (( grab params.vm_type ))

    properties:
      debug: false

    jobs:
      - name: pre-start-script
        release: os-conf
        properties:
          script: |-
            #!/bin/bash
            apt-get update && apt-get install -y wget curl git jq

      - name: docker
        release: docker
        properties:
          tcp_address: 127.0.0.1

      - name: awscliv2
        release: awscli2
        properties:
          aws_access_key_id:     (( grab params.aws_access_key ))
          aws_secret_access_key: (( grab params.aws_secret_key ))
          region:                (( grab params.aws_region ))

      - name: buildkite-agent
        release: buildkite-agent
        properties:
          token: (( grab params.buildkite_token ))
          debug: false
          hooks:
            environment: (( grab params.agent_environment ))
          spawn: 1
          tags: (( grab params.agent_tags || meta.default.tags ))

update:
  serial:            false
  canaries:          1
  max_in_flight:     1
  max_errors:        1
  canary_watch_time: 5000-600000
  update_watch_time: 5000-600000

stemcells:
  - alias:   default
    os:      (( grab params.stemcell_os      || "ubuntu-xenial" ))
    version: (( grab params.stemcell_version || "latest" ))

releases:
  - name:    docker
    version: 35.3.4
    url:     https://bosh.io/d/github.com/cloudfoundry-incubator/docker-boshrelease?v=35.3.4
    sha1:    8dcacf558067ed5302e30e4c8de928ee7917695e

  - name:    os-conf
    version: 22.0.0
    url:     https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=22.0.0
    sha1:    6946056ad69ae378cb89c9ef76daf66370a7dc6a

  - name:    buildkite-agent
    version: 1.0.0
    url:     https://github.com/starkandwayne/buildkite-agent-boshrelease/releases/download/v1.0.0/buildkite-agent-1.0.0.tgz
    sha1:    5bc847a1243ac8c46fe6d0f763f2afc086e9fa46

  - name:    awscli2
    version: 1.0.1
    url:     https://github.com/starkandwayne/awscli2-boshrelease/releases/download/v1.0.1/awscli2-1.0.1.tgz
    sha1:    8a50bbb1b870922a28a86bc8efecbb7a3d7ea341
